language: python
sudo: false
before_script:
- wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.27.zip
- unzip -q google_appengine_1.9.27.zip
install:
- pip install --upgrade pip
- if [[ $TOXENV == 'py32' ]]; then pip install -I 'virtualenv<14.0'; fi
- pip install tox
script:
- tox
python: 3.5
env:
  matrix:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=coveralls-py2
  - TOXENV=coveralls-py3
  - TOXENV=py27 APPENGINE_RUNTIME=python27
  global:
  - secure: BGg68g6mf+VktQNzz+WQ+fbiiuzaLNHqJeXsvuN/JP8BttFVpiRQe4CYQrBIyhyqyDg07l+QGOV/5T1SuzCiRh92YNotem+RbUGvQPc9/kzfYXSmTpwe+d31qlKJ2Gwymlbi6ZTckoDGHtfh29sbHs7mfzTPfQb8untXY0p5w9o= # ALGOLIA_APPLICATION_ID
  - secure: CAoqGDpJIREeeGieVPVvdEnDNPohZl95BEkhH0BHjYX3SLKCf9ZGw1DRcfGEPAwej3EpaUFSk4i1cHrItWll4zuZ6LQ8R/gUmsCrev3vPyFWk2DUTGxInHgPcYKpLTbQF/stgXo3YVSMBZtSky73++shbkS99KJRMGOJCLyvWp4= # ALGOLIA_API_KEY
  - secure: ZL+IUM4D7pJX3yP2lSEaHZpxt+utEbH+wrQ8RwXAvnkwLw5WgU3lP+yS2VEkVH+3b9LZA/b/mbXKZg9Ct/j8CIdbZyRmHhCr9qF5uHrPtLHg+Rono8I8PKyHe1QidLvqo0KQvYRHnGqooVx8nZYi9ue6KEfiAz0WNjpwupqYhow= # ALGOLIA_API_KEY_SEARCH
