language: python
sudo: false
before_script:
- wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.27.zip
- unzip -q google_appengine_1.9.27.zip
install:
- pip install --upgrade pip
- pip install -I 'virtualenv<14.0'
- pip install tox
script:
- tox
python: 3.5
env:
  matrix:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=coveralls-py2
  - TOXENV=coveralls-py3
  - TOXENV=py27 APPENGINE_RUNTIME=python27
  global:
  - secure: S/H779PQk4yKOmP3HbcsrdJjls5cDQDekYhvW0nvlsSkw7L+nqEhV92Lk+JMIPOYeug66NmBSqCIhLC6NHp6TK3Z6y7wNO1JeVdtl+X7b7acRNAkMz9GqkZgLP05LyB1kGUpKfzEejxvKcKQ4iAkEVVu4N5IXcO92Y/IIMuKOe4=
  - secure: Xtw10xjgdPiWrG6BZ+2B1UlkCBEtpVoHwttXj1nmroWqpIGOLDiAHVxgORe+mt4lIvDe2+cWJRRIeuY8f1xkbkR/FjNMf7iGbNJiARvcUe3ivX29cwOCyghN7IliyikHLwhntQcx2UFBDlMyYH5DqZYVzo22IyUFmPBMS58WqO4=
