name: algoliasearch
version: 1.1.0
description: A Dart package for Algolia. Enables seamless integration for instant search, typo tolerance & user insights, and more, in Dart/Flutter apps.
homepage: https://www.algolia.com/doc/
repository: https://github.com/algolia/algoliasearch-client-dart/tree/main/packages/algoliasearch
topics:
  - search
  - discovery

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  algolia_client_core: ^1.1.0
  algolia_client_search: ^1.1.0
  algolia_client_insights: ^1.1.0
  json_annotation: ^4.8.1
  collection: ^1.17.1

dev_dependencies:
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  lints: ^3.0.0
  logging: ^1.2.0
  test: ^1.24.3